export enum StatoProdotto {
    DISPONIBILE = "DISPONIBILE",
    NON_DISPONIBILE = "NON_DISPONIBILE",
    VENDUTO = "VENDUTO",
    FUORI_PRODUZIONE = "FUORI_PRODUZIONE",
    IN_PROMOZIONE = "IN_PROMOZIONE"
}
  